name: dominic_flutter_template
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # HELPER
  equatable: ^2.0.5
  intl: 0.18.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  device_info_plus: ^10.1.0
  package_info_plus: ^7.0.0
  logger: ^2.2.0
  device_preview: ^1.1.0
  permission_handler: ^11.3.1
  # STATE MANAGEMENT
  flutter_bloc: ^8.1.5
  get_it: ^7.4.8
  go_router: ^13.2.3
  # WIDGET
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  # FIREBASE
  firebase_core: ^2.30.0
  firebase_analytics: ^10.10.2
  firebase_app_check: ^0.2.2+2
  firebase_crashlytics: ^3.5.2
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  firebase_remote_config: ^4.4.2
  firebase_messaging: ^14.8.2
  firebase_storage: ^11.7.2
  cloud_firestore: ^4.17.0
  firebase_dynamic_links: ^5.5.2

  flutter_local_notifications: ^17.1.0
  sign_in_with_apple: ^6.1.0
  uni_links: ^0.5.1
  flutter_facebook_auth: ^6.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0


flutter:

  uses-material-design: true

# Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    # - assets/images/
    - assets/images/locale/
    - assets/lotties/
    # - assets/svgs/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans.ttf
    - family: OpenSans-Italic
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/open_sans/static/OpenSans-Bold.ttf
