name: dominic_flutter_template
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # HELPER
  equatable: ^2.0.5
  intl: 0.18.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  # STATE MANAGEMENT
  flutter_bloc: ^8.1.5
  get_it: ^7.4.8
  go_router: ^13.2.3
  # WIDGET
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0


flutter:

  uses-material-design: true

# Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    # - assets/images/
    - assets/images/locale/
    # - assets/lotties/
    # - assets/svgs/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans.ttf
    - family: OpenSans-Italic
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/open_sans/static/OpenSans-Bold.ttf
