// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_develop.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWy4MExiUVsXpFGdHhYH6K_8aDA5Pew7E',
    appId: '1:35415686723:web:7a7ac57dfdebc480f25ef6',
    messagingSenderId: '35415686723',
    projectId: 'flutter-template-develop-75758',
    authDomain: 'flutter-template-develop-75758.firebaseapp.com',
    storageBucket: 'flutter-template-develop-75758.appspot.com',
    measurementId: 'G-K01M9MK4SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX33mvS2GFG2Z6og8RxjwoXY-QTo7rW_8',
    appId: '1:35415686723:android:34136945d319c71ff25ef6',
    messagingSenderId: '35415686723',
    projectId: 'flutter-template-develop-75758',
    storageBucket: 'flutter-template-develop-75758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKmbUel8cGSHHa3eTPKBxHqH1FtbYk00',
    appId: '1:35415686723:ios:9e050d16721f4399f25ef6',
    messagingSenderId: '35415686723',
    projectId: 'flutter-template-develop-75758',
    storageBucket: 'flutter-template-develop-75758.appspot.com',
    iosBundleId: 'com.example.dominicFlutterTemplate.dev',
  );
}
