// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaEZwNB6-VGuvuGCjC1mNL58dIvhmjy2A',
    appId: '1:723532745982:web:cc8a34b2f637faea06e9af',
    messagingSenderId: '723532745982',
    projectId: 'flutter-template-f3a46',
    authDomain: 'flutter-template-f3a46.firebaseapp.com',
    storageBucket: 'flutter-template-f3a46.appspot.com',
    measurementId: 'G-8MZVH2CP5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTmw_L5lFtJ3nclNlFoghKjHAJ-8D7hhw',
    appId: '1:723532745982:android:4143139bc683354606e9af',
    messagingSenderId: '723532745982',
    projectId: 'flutter-template-f3a46',
    storageBucket: 'flutter-template-f3a46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaorD4jUZYHhoRalZZNqecoYL4O3gAwHU',
    appId: '1:723532745982:ios:36f9081fce7db6f806e9af',
    messagingSenderId: '723532745982',
    projectId: 'flutter-template-f3a46',
    storageBucket: 'flutter-template-f3a46.appspot.com',
    iosBundleId: 'com.example.dominicFlutterTemplate',
  );
}
